export const MessagingPatterns = () => {
  return (
    <div
      id="w-node-_4c58b044-af72-a524-b762-78a0de616c14-8900d6f2"
      className="html-embed svgholder"
    >
      <div className="io-square-animation w-135 h-160 relative inline-block origin-top-left">
        <div className="animation--bottom absolute">
          <div id="sendReceive" className="io-messageIcon" />
          <div id="sendReceive1" className="io-messageIcon" />
          <div id="sendReceive2" className="io-messageIcon" />
          <SvgEight />
        </div>
        <div className="animation--top absolute">
          <div id="pubSub1" className="io-messageIcon" />
          <div id="pubSub2" className="io-messageIcon" />
          <div id="pubSub3" className="io-messageIcon" />
          <div id="received1" className="io-messageIcon" />
          <div id="received2" className="io-messageIcon" />
          <SvgNine />
        </div>
      </div>
    </div>
  )
}

const SvgEight = () => {
  return (
    <svg
      version="1.1"
      id="Layer_1"
      xmlns="http://www.w3.org/2000/svg"
      x="0px"
      y="0px"
      viewBox="0 0 540 600"
      enable-background="new 0 0 540 600"
      width="540px"
      height="640px"
    >
      <g>
        <text
          transform="matrix(1 0 0 1 244.0237 163.1031)"
          fill="#FFFFFF"
          font-family="sans-serif"
          font-size="14px"
        >
          BROKER
        </text>
        <g>
          <rect
            x="236.1"
            y="23.1"
            fill="none"
            width="67.9"
            height="14.9"
          ></rect>
          <text
            transform="matrix(1 0 0 1 243.7923 33.1031)"
            fill="#FFFFFF"
            font-family="sans-serif"
            font-size="14px"
          >
            CLIENTS
          </text>
        </g>
        <circle
          opacity="0.25"
          fill="none"
          stroke="#DA63F7"
          stroke-width="4"
          stroke-linecap="round"
          stroke-miterlimit="10"
          stroke-dasharray="3,12"
          enable-background="new"
          cx="270"
          cy="285.4"
          r="240"
        />
        <circle
          opacity="0.25"
          fill="none"
          stroke="#DA63F7"
          stroke-width="4"
          stroke-linecap="round"
          stroke-miterlimit="10"
          stroke-dasharray="3,12"
          enable-background="new"
          cx="270"
          cy="285.4"
          r="110"
        />
        <path
          opacity="0.75"
          fill="none"
          stroke="#1F062C"
          stroke-width="6"
          stroke-linecap="round"
          stroke-miterlimit="10"
          enable-background="new"
          d="M374.6,319.4c-14.3,44.1-55.8,76-104.6,76c-48.9,0-90.3-31.9-104.6-76"
        />
        <path
          opacity="0.75"
          fill="none"
          stroke="#F96E53"
          stroke-width="4"
          stroke-linecap="round"
          stroke-miterlimit="10"
          stroke-dasharray="3,12"
          enable-background="new"
          d="M374.6,319.4c-14.3,44.1-55.8,76-104.6,76c-48.9,0-90.3-31.9-104.6-76"
        />
        <rect
          x="236.1"
          y="153.1"
          fill="none"
          width="67.9"
          height="14.9"
        />
      </g>
      <line
        fill="none"
        stroke="#DA63F7"
        stroke-opacity="0.25"
        stroke-width="4"
        stroke-linecap="round"
        stroke-miterlimit="10"
        stroke-dasharray="3,12"
        x1="270"
        y1="394.5"
        x2="270"
        y2="525.4"
      />
      <line
        opacity="0.75"
        fill="none"
        stroke="#F96E53"
        stroke-width="4"
        stroke-linecap="round"
        stroke-miterlimit="10"
        stroke-dasharray="3,12"
        enable-background="new"
        x1="374.6"
        y1="319.4"
        x2="498.3"
        y2="359.6"
      />
      <line
        fill="none"
        stroke="#DA63F7"
        stroke-opacity="0.25"
        stroke-width="4"
        stroke-linecap="round"
        stroke-miterlimit="10"
        stroke-dasharray="3,12"
        x1="334.4"
        y1="196.8"
        x2="411.1"
        y2="91.3"
      />
      <line
        fill="none"
        stroke="#F96E53"
        stroke-width="4"
        stroke-linecap="round"
        stroke-miterlimit="10"
        stroke-dasharray="3,12"
        enable-background="new"
        x1="166"
        y1="319.2"
        x2="41.1"
        y2="359.8"
      />
      <line
        fill="none"
        stroke="#DA63F7"
        stroke-opacity="0.25"
        stroke-width="4"
        stroke-linecap="round"
        stroke-miterlimit="10"
        stroke-dasharray="3,12"
        x1="204.8"
        y1="195.8"
        x2="127.2"
        y2="88.9"
      />
      <g>
        <circle
          fill="#1F062C"
          stroke="#DA63F7"
          stroke-opacity="0.25"
          stroke-width="4"
          stroke-linecap="round"
          stroke-miterlimit="10"
          cx="126"
          cy="89.8"
          r="20"
        />
      </g>
      <g>
        <circle
          fill="#1F062C"
          stroke="#F96E53"
          stroke-width="4"
          stroke-linecap="round"
          stroke-miterlimit="10"
          cx="41"
          cy="359.8"
          r="20"
        />
      </g>
      <g>
        <circle
          fill="#1F062C"
          stroke="#DA63F7"
          stroke-opacity="0.25"
          stroke-width="4"
          stroke-linecap="round"
          stroke-miterlimit="10"
          cx="270"
          cy="525.4"
          r="20"
        />
      </g>
      <g>
        <circle
          fill="#1F062C"
          stroke="#F96E53"
          stroke-width="4"
          stroke-linecap="round"
          stroke-miterlimit="10"
          cx="499"
          cy="359.8"
          r="20"
        />
      </g>
      <g>
        <circle
          fill="#1F062C"
          stroke="#DA63F7"
          stroke-opacity="0.25"
          stroke-width="4"
          stroke-linecap="round"
          stroke-miterlimit="10"
          cx="411.5"
          cy="92"
          r="20"
        />
      </g>
      <g>
        <text
          transform="matrix(1 0 0 1 412.0005 138.0864)"
          fill="#DA63F7"
          fill-opacity="0.25"
          font-family="sans-serif"
          font-size="14px"
        >
          SUBSCRIBER
        </text>
      </g>
      <g>
        <text
          transform="matrix(1 0 0 1 396.5795 374.5344)"
          fill="#F96E53"
          font-family="sans-serif"
          font-size="14px"
        >
          REQUEST
        </text>
      </g>
      <text
        transform="matrix(1 0 0 1 75.0228 374.5343)"
        fill="#F96E53"
        font-family="sans-serif"
        font-size="14px"
      >
        REPLY
      </text>
      <g>
        <text
          transform="matrix(1 0 0 1 286.0379 485.3071)"
          fill="#DA63F7"
          fill-opacity="0.25"
          font-family="sans-serif"
          font-size="14px"
        >
          SUBSCRIBER
        </text>
      </g>
      <text
        transform="matrix(1 0 0 1 160 98.4676)"
        fill="#DA63F7"
        fill-opacity="0.25"
        font-family="sans-serif"
        font-size="14px"
      >
        PUBLISHER
      </text>
    </svg>
  )
}

const SvgNine = () => {
  return (
    <svg
      version="1.1"
      id="Layer_1"
      xmlns="http://www.w3.org/2000/svg"
      x="0px"
      y="0px"
      viewBox="0 0 540 600"
      enable-background="new 0 0 540 600"
      // space="preserve"
      width="540px"
      height="640px"
    >
      <g>
        <text
          transform="matrix(1 0 0 1 244.0237 163.1031)"
          fill="#FFFFFF"
          font-family="sans-serif"
          font-size="14px"
        >
          BROKER
        </text>
        <g>
          <rect
            x="236.1"
            y="23.1"
            fill="none"
            width="67.9"
            height="14.9"
          ></rect>
          <text
            transform="matrix(1 0 0 1 243.7923 33.1031)"
            fill="#FFFFFF"
            font-family="sans-serif"
            font-size="14px"
          >
            CLIENTS
          </text>
        </g>
        <circle
          opacity="0.25"
          fill="none"
          stroke="#DA63F7"
          stroke-width="4"
          stroke-linecap="round"
          stroke-miterlimit="10"
          stroke-dasharray="3,12"
          enable-background="new"
          cx="270"
          cy="285.4"
          r="240"
        ></circle>
        <path
          fill="none"
          stroke="#0092FF"
          stroke-width="4"
          stroke-linecap="round"
          stroke-miterlimit="10"
          stroke-dasharray="3,12"
          d="
        M205.3,196.4c18.2-13.2,40.5-21,64.7-21c24.2,0,46.5,7.8,64.7,21"
        ></path>
        <path
          fill="none"
          stroke="#0092FF"
          stroke-width="4"
          stroke-linecap="round"
          stroke-miterlimit="10"
          stroke-dasharray="3,12"
          d="
        M270,395.4c-60.8,0-110-49.2-110-110c0-36.6,17.8-68.9,45.3-89"
        ></path>

        <path
          opacity="0.75"
          fill="none"
          stroke="#DA63F7"
          stroke-opacity="0.5"
          stroke-width="4"
          stroke-linecap="round"
          stroke-miterlimit="10"
          stroke-dasharray="3,12"
          enable-background="new"
          d="
        M334.7,196.4c27.5,20,45.3,52.4,45.3,89c0,60.8-49.2,110-110,110"
        ></path>
        <rect
          x="236.1"
          y="153.1"
          fill="none"
          width="67.9"
          height="14.9"
        ></rect>
      </g>
      <line
        fill="none"
        stroke="#0092FF"
        stroke-width="4"
        stroke-linecap="round"
        stroke-miterlimit="10"
        stroke-dasharray="3,12"
        x1="270"
        y1="394.5"
        x2="270"
        y2="525.4"
      ></line>
      <line
        opacity="0.75"
        fill="none"
        stroke="#DA63F7"
        stroke-opacity="0.5"
        stroke-width="4"
        stroke-linecap="round"
        stroke-miterlimit="10"
        stroke-dasharray="3,12"
        enable-background="new"
        x1="374.6"
        y1="319.4"
        x2="498.3"
        y2="359.6"
      ></line>
      <path
        fill="#1F062C"
        stroke="#DA63F7"
        stroke-width="4"
        stroke-linecap="round"
        stroke-miterlimit="10"
        d="M477.4,0"
      ></path>
      <line
        fill="none"
        stroke="#0092FF"
        stroke-width="4"
        stroke-linecap="round"
        stroke-miterlimit="10"
        stroke-dasharray="3,12"
        x1="334.4"
        y1="196.8"
        x2="411.1"
        y2="91.3"
      ></line>
      <line
        opacity="0.75"
        fill="none"
        stroke="#DA63F7"
        stroke-opacity="0.5"
        stroke-width="4"
        stroke-linecap="round"
        stroke-miterlimit="10"
        stroke-dasharray="3,12"
        enable-background="new"
        x1="166"
        y1="319.2"
        x2="41.1"
        y2="359.8"
      ></line>
      <path
        fill="#1F062C"
        stroke="#DA63F7"
        stroke-width="4"
        stroke-linecap="round"
        stroke-miterlimit="10"
        d="M62.6,0"
      ></path>
      <line
        fill="none"
        stroke="#0092FF"
        stroke-width="4"
        stroke-linecap="round"
        stroke-miterlimit="10"
        stroke-dasharray="3,12"
        x1="204.8"
        y1="195.8"
        x2="127.2"
        y2="88.9"
      ></line>
      <g>
        <circle
          fill="#1F062C"
          stroke="#0092FF"
          stroke-width="4"
          stroke-linecap="round"
          stroke-miterlimit="10"
          cx="126"
          cy="89.8"
          r="20"
        ></circle>
      </g>
      <g>
        <circle
          fill="#1F062C"
          stroke="#DA63F7"
          stroke-opacity="0.25"
          stroke-width="4"
          stroke-linecap="round"
          stroke-miterlimit="10"
          cx="41"
          cy="359.8"
          r="20"
        ></circle>
      </g>
      <g>
        <circle
          fill="#1F062C"
          stroke="#0092FF"
          stroke-width="4"
          stroke-linecap="round"
          stroke-miterlimit="10"
          cx="270"
          cy="525.4"
          r="20"
        ></circle>
      </g>
      <g>
        <circle
          fill="#1F062C"
          stroke="#DA63F7"
          stroke-opacity="0.25"
          stroke-width="4"
          stroke-linecap="round"
          stroke-miterlimit="10"
          cx="499"
          cy="359.8"
          r="20"
        ></circle>
      </g>
      <g>
        <circle
          fill="#1F062C"
          stroke="#0092FF"
          stroke-width="4"
          stroke-linecap="round"
          stroke-miterlimit="10"
          cx="411.5"
          cy="92"
          r="20"
        ></circle>
      </g>
      <g>
        <text
          transform="matrix(1 0 0 1 412.0005 138.0864)"
          fill="#0092FF"
          font-family="sans-serif"
          font-size="14px"
        >
          SUBSCRIBER
        </text>
      </g>
      <g>
        <text
          transform="matrix(1 0 0 1 396.5795 374.5344)"
          fill="#DA63F7"
          fill-opacity="0.25"
          font-family="sans-serif"
          font-size="14px"
        >
          REQUEST
        </text>
      </g>
      <text
        transform="matrix(1 0 0 1 75.0228 374.5343)"
        fill="#DA63F7"
        fill-opacity="0.25"
        font-family="sans-serif"
        font-size="14px"
      >
        REPLY
      </text>
      <g>
        <text
          transform="matrix(1 0 0 1 286.0379 485.3071)"
          fill="#0092FF"
          font-family="sans-serif"
          font-size="14px"
        >
          SUBSCRIBER
        </text>
      </g>
      <text
        transform="matrix(1 0 0 1 160 98.4676)"
        fill="#0092FF"
        font-family="sans-serif"
        font-size="14px"
      >
        PUBLISHER
      </text>
    </svg>
  )
}
